image:
  repository: nitheesh86/microservice-frontend
  tag: 1.0.10

replicaCount: 2

service:
  type: NodePort
  port: 30080
  nodePort: 30080

resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
