apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-prod
  namespace: argocd
spec:
  project: craftista
  sources:
    - repoURL: https://github.com/vchandela/gitops-for-dummies
      targetRevision: main
      path: service-charts/catalogue-db
      helm:
        valueFiles:
          - $values/env/prod/catalogue-db/catalogue-db-values.yaml
    - repoURL: https://github.com/vchandela/gitops-for-dummies
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
