apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:catalogue-prod-stage
spec:
  project: craftista
  sources:
    - repoURL: https://github.com/vchandela/gitops-for-dummies
      targetRevision: main
      path: service-charts/catalogue
      helm:
        valueFiles:
          - $values/env/prod/catalogue/catalogue-values.yaml
    - repoURL: https://github.com/vchandela/gitops-for-dummies
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
